//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoList_v1.lib.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLists
    {
        public int id { get; set; }
        public Nullable<int> cUserId { get; set; }
        public string cName { get; set; }
        public bool isDone { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
