//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoList_v1.lib.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbUsers()
        {
            this.tbLists = new HashSet<tbLists>();
        }
    
        public int id { get; set; }
        public string cLogin { get; set; }
        public string cPassword { get; set; }
        public Nullable<System.Guid> cToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLists> tbLists { get; set; }
    }
}
