//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoList.lib.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLists
    {
        public int id { get; set; }
        public string cName { get; set; }
        public bool isDone { get; set; }
    }
}
